# Generated by Django 4.1.3 on 2022-11-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Hero', models.CharField(max_length=200)),
                ('Race', models.CharField(max_length=200)),
                ('Strength', models.IntegerField()),
                ('Constitution', models.IntegerField()),
                ('Dexterity', models.IntegerField()),
                ('Intelligence', models.IntegerField()),
                ('Wisdom', models.IntegerField()),
                ('Charisma', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
